"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KWot8TTw4Qb
 */
import { Search } from "./Search";
import React, { useEffect, useState } from "react";

interface Company {
  cik: string;
  name: string;
}

export function XBRL() {
  const [company, setCompany] = React.useState<Company | null>(null);
  return (
    <div className="flex flex-col min-h-screen min-w-[1240px]">
      <header className="border-b">
        <div className="container px-4 py-2 md:py-4 lg:py-6">
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <BarChartIcon className="h-6 w-6 text-blue-500" />
              <h1 className="text-xl font-bold tracking-tight">
                SEC XBRL API Explorer
              </h1>
            </div>
            <div className="flex-1">
              <div className="w-full m-auto rounded-lg">
                <Search entity={company} setEntity={setCompany} />
              </div>
            </div>
          </div>
        </div>
      </header>
      <main className="flex-1 py-4">
        <div className="container grid gap-4 px-4 text-sm md:gap-8 md:px-6 min-w-full">
          <CompanyInfo company={company} />
          <CompanyFacts company={company} />
          <div className="border rounded-lg overflow-auto max-h-[400px]">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b">
                  <th className="px-2 py-2">Name</th>
                  <th className="px-2 py-2">Value</th>
                  <th className="px-2 py-2">Additional Information</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b">
                  <td className="px-2 py-2">Net Income</td>
                  <td className="px-2 py-2">$1,000,000</td>
                  <td className="px-2 py-2">Fiscal Year 2022</td>
                </tr>
                <tr className="border-b bg-gray-100 dark:bg-gray-800">
                  <td className="px-2 py-2">Revenue</td>
                  <td className="px-2 py-2">$5,000,000</td>
                  <td className="px-2 py-2">Fiscal Year 2022</td>
                </tr>
                <tr className="border-b">
                  <td className="px-2 py-2">Total Assets</td>
                  <td className="px-2 py-2">$10,000,000</td>
                  <td className="px-2 py-2">Fiscal Year 2022</td>
                </tr>
                <tr className="border-b bg-gray-100 dark:bg-gray-800">
                  <td className="px-2 py-2">Total Liabilities</td>
                  <td className="px-2 py-2">$3,000,000</td>
                  <td className="px-2 py-2">Fiscal Year 2022</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
}

function CompanyInfo({ company }: { company: Company | null }) {
  if (company === null) return <></>;
  const edgarUrl = `https://www.sec.gov/edgar/browse/?CIK=${company.cik}`;
  return (
    <div className="grid gap-2">
      <h2 className="font-semibold">{company.name}</h2>
      <p className="text-sm">Central Index Key (CIK): {company.cik}</p>
      <div>
        EDGAR page:{" "}
        <a
          href={edgarUrl}
          className="text-blue-500 no-underline hover:text-blue-700"
        >
          {edgarUrl}
        </a>
      </div>
    </div>
  );
}

function CompanyFacts({ company }: { company: Company | null }) {
  const [companyFacts, setCompanyFacts] = useState(null);

  useEffect(() => {
    async function fetchData() {
      if (company === null) return;
      const res = await fetch(`/api/companyfacts?cik=${company.cik}`);
      const data = await res.json();
      setCompanyFacts(data.facts);
    }
    fetchData();
  }, [company]); // Empty dependency array means this effect runs once on mount

  if (company === null) return;
  if (!companyFacts) return <div>Loading...</div>;

  // Render your component with companyFacts data
  return <XbrlFacts facts={companyFacts}></XbrlFacts>;
}

function XbrlFacts({ facts }: any) {
  return (
    <section className="flex flex-col space-y-4">
      {Object.entries(facts).map(([key, value]: any[]) => (
        <article key={key} className="space-y-2">
          <h2 className="text-xl font-bold text-gray-900">{key}</h2>
          {Object.values(value).map(({ label, description }: any) => (
            <div className="bg-white shadow sm:rounded-lg" key={label}>
              <div className="px-4 py-5 sm:p-6">
                <h3 className="text-lg leading-6 font-medium text-gray-900">
                  {label}
                </h3>
                <p className="mt-1 max-w-2xl text-sm text-gray-500">
                  {description}
                </p>
              </div>
            </div>
          ))}
        </article>
      ))}
    </section>
  );
}

function BarChartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  );
}
